name: provision infrastructure on creation
on:
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  infra-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0.4.0'
      with:
        token_format: 'access_token'
        project_id: "white-resolver-460502-v9"
        workload_identity_provider: 'projects/211464305662/locations/global/workloadIdentityPools/github/providers/github-provider'
        service_account: '211464305662-compute@developer.gserviceaccount.com'
    
    - uses: hashicorp/setup-terraform@v3

    - name: terraform init
      run: terraform init
    
    - name: terraform plan
      run: terraform plan

    #- name: terraform apply
     # run: terraform apply -auto-approve
    - name: terraform destroy
      run: terraform destroy -auto-approve -input=false
